//package eu.modaclouds.db.models;
//
//import java.io.Serializable;
//import java.util.ArrayList;
//import java.util.HashMap;
//import java.util.List;
//
///**
// * @author Marco Scavuzzo
// *
// */
//public class Metamodel implements Serializable{
//
//	String partitionGroup;
//	List<String> columnFamilies;
//	String rowKey;
//	//List of columns contained by a given column Family
//	HashMap<String, List<Column>> columns;
//	
//	/**
//	 * Constructs a Metamodel Object, instantiating the columns hashmap and the columnfamilies list to the 
//	 * respective empty values
//	 */
//	public Metamodel(){
//		this.columns = new HashMap<String, List<Column>>();
//		this.columnFamilies = new ArrayList<String>();
//	}
//	/**
//	 * Gets a list of the columns for a given column family
//	 * @param columnFamily A column family name
//	 * @return list of the columns 
//	 */
//	public List<Column> getColumnsByColumnFamily(String columnFamily){
//		return columns.get(columnFamily);
//	}
//	/**
//	 * Sets the columns to be contained in a column family
//	 * @param columnFamily The column family name that will contain the columns
//	 * @param columnList A list of columns
//	 */
//	public void setColumnsByColumnFamily(String columnFamily, List<Column> columnList){
//		columns.put(columnFamily, columnList);
//	}
//	
//	/**
//	 * Adds a column family to the column families list
//	 * @param columnFamily
//	 */
//	public void addColumnFamily(String columnFamily){
//		columnFamilies.add(columnFamily);
//	}
//	
//	
//	/**
//	 * Gets the name of the partition group
//	 * @return the name of the partition group
//	 */
//	public String getPartitionGroup() {
//		return partitionGroup;
//	}
//
//	/**
//	 * Sets the name of the partition group
//	 * @param partitionGroup The name of the partition group to be set
//	 */
//	public void setPartitionGroup(String partitionGroup) {
//		this.partitionGroup = partitionGroup;
//	}
//
//	/**
//	 * Gets a list of the column families contained in the model
//	 * @return The list of column families
//	 */
//	public List<String> getColumnFamilies() {
//		return columnFamilies;
//	}
//
//	public void setColumnFamilies(List<String> columnFamilies) {
//		this.columnFamilies = columnFamilies;
//	}
//
//	public String getRowKey() {
//		return rowKey;
//	}
//
//	public void setRowKey(String rowKey) {
//		this.rowKey = rowKey;
//	}
//
//	public HashMap<String, List<Column>> getColumns() {
//		return columns;
//	}
//
//	public void setColumns(HashMap<String, List<Column>> columns) {
//		this.columns = columns;
//	}
//
//}


/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package eu.modaclouds.db.models;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Metamodel implements org.apache.thrift.TBase<Metamodel, Metamodel._Fields>, java.io.Serializable, Cloneable, Comparable<Metamodel> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Metamodel");

  private static final org.apache.thrift.protocol.TField PARTITION_GROUP_FIELD_DESC = new org.apache.thrift.protocol.TField("partitionGroup", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField COLUMN_FAMILIES_FIELD_DESC = new org.apache.thrift.protocol.TField("columnFamilies", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField ROW_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("rowKey", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField COLUMNS_FIELD_DESC = new org.apache.thrift.protocol.TField("columns", org.apache.thrift.protocol.TType.MAP, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MetamodelStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MetamodelTupleSchemeFactory());
  }

  public String partitionGroup; // required
  public List<String> columnFamilies; // optional
  public String rowKey; // required
  public Map<String,List<Column>> columns; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PARTITION_GROUP((short)1, "partitionGroup"),
    COLUMN_FAMILIES((short)2, "columnFamilies"),
    ROW_KEY((short)3, "rowKey"),
    COLUMNS((short)4, "columns");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PARTITION_GROUP
          return PARTITION_GROUP;
        case 2: // COLUMN_FAMILIES
          return COLUMN_FAMILIES;
        case 3: // ROW_KEY
          return ROW_KEY;
        case 4: // COLUMNS
          return COLUMNS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.COLUMN_FAMILIES};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PARTITION_GROUP, new org.apache.thrift.meta_data.FieldMetaData("partitionGroup", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COLUMN_FAMILIES, new org.apache.thrift.meta_data.FieldMetaData("columnFamilies", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.ROW_KEY, new org.apache.thrift.meta_data.FieldMetaData("rowKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COLUMNS, new org.apache.thrift.meta_data.FieldMetaData("columns", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Column.class)))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Metamodel.class, metaDataMap);
  }

  public Metamodel() {
	this.columns = new HashMap<String, List<Column>>();
	this.columnFamilies = new ArrayList<String>();
  }

  public Metamodel(
    String partitionGroup,
    String rowKey,
    Map<String,List<Column>> columns)
  {
    this();
    this.partitionGroup = partitionGroup;
    this.rowKey = rowKey;
    this.columns = columns;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Metamodel(Metamodel other) {
    if (other.isSetPartitionGroup()) {
      this.partitionGroup = other.partitionGroup;
    }
    if (other.isSetColumnFamilies()) {
      List<String> __this__columnFamilies = new ArrayList<String>(other.columnFamilies);
      this.columnFamilies = __this__columnFamilies;
    }
    if (other.isSetRowKey()) {
      this.rowKey = other.rowKey;
    }
    if (other.isSetColumns()) {
      Map<String,List<Column>> __this__columns = new HashMap<String,List<Column>>(other.columns.size());
      for (Map.Entry<String, List<Column>> other_element : other.columns.entrySet()) {

        String other_element_key = other_element.getKey();
        List<Column> other_element_value = other_element.getValue();

        String __this__columns_copy_key = other_element_key;

        List<Column> __this__columns_copy_value = new ArrayList<Column>(other_element_value.size());
        for (Column other_element_value_element : other_element_value) {
          __this__columns_copy_value.add(new Column(other_element_value_element));
        }

        __this__columns.put(__this__columns_copy_key, __this__columns_copy_value);
      }
      this.columns = __this__columns;
    }
  }

  public Metamodel deepCopy() {
    return new Metamodel(this);
  }

  @Override
  public void clear() {
    this.partitionGroup = null;
    this.columnFamilies = null;
    this.rowKey = null;
    this.columns = null;
  }

  public String getPartitionGroup() {
    return this.partitionGroup;
  }

  public Metamodel setPartitionGroup(String partitionGroup) {
    this.partitionGroup = partitionGroup;
    return this;
  }

  public void unsetPartitionGroup() {
    this.partitionGroup = null;
  }

  /** Returns true if field partitionGroup is set (has been assigned a value) and false otherwise */
  public boolean isSetPartitionGroup() {
    return this.partitionGroup != null;
  }

  public void setPartitionGroupIsSet(boolean value) {
    if (!value) {
      this.partitionGroup = null;
    }
  }

  public int getColumnFamiliesSize() {
    return (this.columnFamilies == null) ? 0 : this.columnFamilies.size();
  }

  public java.util.Iterator<String> getColumnFamiliesIterator() {
    return (this.columnFamilies == null) ? null : this.columnFamilies.iterator();
  }

  public void addToColumnFamilies(String elem) {
    if (this.columnFamilies == null) {
      this.columnFamilies = new ArrayList<String>();
    }
    this.columnFamilies.add(elem);
  }

  public List<String> getColumnFamilies() {
    return this.columnFamilies;
  }

  public Metamodel setColumnFamilies(List<String> columnFamilies) {
    this.columnFamilies = columnFamilies;
    return this;
  }

  public void unsetColumnFamilies() {
    this.columnFamilies = null;
  }

  /** Returns true if field columnFamilies is set (has been assigned a value) and false otherwise */
  public boolean isSetColumnFamilies() {
    return this.columnFamilies != null;
  }

  public void setColumnFamiliesIsSet(boolean value) {
    if (!value) {
      this.columnFamilies = null;
    }
  }

  public String getRowKey() {
    return this.rowKey;
  }

  public Metamodel setRowKey(String rowKey) {
    this.rowKey = rowKey;
    return this;
  }

  public void unsetRowKey() {
    this.rowKey = null;
  }

  /** Returns true if field rowKey is set (has been assigned a value) and false otherwise */
  public boolean isSetRowKey() {
    return this.rowKey != null;
  }

  public void setRowKeyIsSet(boolean value) {
    if (!value) {
      this.rowKey = null;
    }
  }

  public int getColumnsSize() {
    return (this.columns == null) ? 0 : this.columns.size();
  }

  public void putToColumns(String key, List<Column> val) {
    if (this.columns == null) {
      this.columns = new HashMap<String,List<Column>>();
    }
    this.columns.put(key, val);
  }

  public Map<String,List<Column>> getColumns() {
    return this.columns;
  }

  public Metamodel setColumns(Map<String,List<Column>> columns) {
    this.columns = columns;
    return this;
  }

  public void unsetColumns() {
    this.columns = null;
  }

  /** Returns true if field columns is set (has been assigned a value) and false otherwise */
  public boolean isSetColumns() {
    return this.columns != null;
  }

  public void setColumnsIsSet(boolean value) {
    if (!value) {
      this.columns = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PARTITION_GROUP:
      if (value == null) {
        unsetPartitionGroup();
      } else {
        setPartitionGroup((String)value);
      }
      break;

    case COLUMN_FAMILIES:
      if (value == null) {
        unsetColumnFamilies();
      } else {
        setColumnFamilies((List<String>)value);
      }
      break;

    case ROW_KEY:
      if (value == null) {
        unsetRowKey();
      } else {
        setRowKey((String)value);
      }
      break;

    case COLUMNS:
      if (value == null) {
        unsetColumns();
      } else {
        setColumns((Map<String,List<Column>>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PARTITION_GROUP:
      return getPartitionGroup();

    case COLUMN_FAMILIES:
      return getColumnFamilies();

    case ROW_KEY:
      return getRowKey();

    case COLUMNS:
      return getColumns();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PARTITION_GROUP:
      return isSetPartitionGroup();
    case COLUMN_FAMILIES:
      return isSetColumnFamilies();
    case ROW_KEY:
      return isSetRowKey();
    case COLUMNS:
      return isSetColumns();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Metamodel)
      return this.equals((Metamodel)that);
    return false;
  }

  public boolean equals(Metamodel that) {
    if (that == null)
      return false;

    boolean this_present_partitionGroup = true && this.isSetPartitionGroup();
    boolean that_present_partitionGroup = true && that.isSetPartitionGroup();
    if (this_present_partitionGroup || that_present_partitionGroup) {
      if (!(this_present_partitionGroup && that_present_partitionGroup))
        return false;
      if (!this.partitionGroup.equals(that.partitionGroup))
        return false;
    }

    boolean this_present_columnFamilies = true && this.isSetColumnFamilies();
    boolean that_present_columnFamilies = true && that.isSetColumnFamilies();
    if (this_present_columnFamilies || that_present_columnFamilies) {
      if (!(this_present_columnFamilies && that_present_columnFamilies))
        return false;
      if (!this.columnFamilies.equals(that.columnFamilies))
        return false;
    }

    boolean this_present_rowKey = true && this.isSetRowKey();
    boolean that_present_rowKey = true && that.isSetRowKey();
    if (this_present_rowKey || that_present_rowKey) {
      if (!(this_present_rowKey && that_present_rowKey))
        return false;
      if (!this.rowKey.equals(that.rowKey))
        return false;
    }

    boolean this_present_columns = true && this.isSetColumns();
    boolean that_present_columns = true && that.isSetColumns();
    if (this_present_columns || that_present_columns) {
      if (!(this_present_columns && that_present_columns))
        return false;
      if (!this.columns.equals(that.columns))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Metamodel other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPartitionGroup()).compareTo(other.isSetPartitionGroup());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPartitionGroup()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.partitionGroup, other.partitionGroup);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetColumnFamilies()).compareTo(other.isSetColumnFamilies());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetColumnFamilies()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.columnFamilies, other.columnFamilies);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRowKey()).compareTo(other.isSetRowKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRowKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rowKey, other.rowKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetColumns()).compareTo(other.isSetColumns());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetColumns()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.columns, other.columns);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Metamodel(");
    boolean first = true;

    sb.append("partitionGroup:");
    if (this.partitionGroup == null) {
      sb.append("null");
    } else {
      sb.append(this.partitionGroup);
    }
    first = false;
    if (isSetColumnFamilies()) {
      if (!first) sb.append(", ");
      sb.append("columnFamilies:");
      if (this.columnFamilies == null) {
        sb.append("null");
      } else {
        sb.append(this.columnFamilies);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("rowKey:");
    if (this.rowKey == null) {
      sb.append("null");
    } else {
      sb.append(this.rowKey);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("columns:");
    if (this.columns == null) {
      sb.append("null");
    } else {
      sb.append(this.columns);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MetamodelStandardSchemeFactory implements SchemeFactory {
    public MetamodelStandardScheme getScheme() {
      return new MetamodelStandardScheme();
    }
  }

  private static class MetamodelStandardScheme extends StandardScheme<Metamodel> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Metamodel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PARTITION_GROUP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.partitionGroup = iprot.readString();
              struct.setPartitionGroupIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COLUMN_FAMILIES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.columnFamilies = new ArrayList<String>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  String _elem2;
                  _elem2 = iprot.readString();
                  struct.columnFamilies.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setColumnFamiliesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ROW_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.rowKey = iprot.readString();
              struct.setRowKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // COLUMNS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map3 = iprot.readMapBegin();
                struct.columns = new HashMap<String,List<Column>>(2*_map3.size);
                for (int _i4 = 0; _i4 < _map3.size; ++_i4)
                {
                  String _key5;
                  List<Column> _val6;
                  _key5 = iprot.readString();
                  {
                    org.apache.thrift.protocol.TList _list7 = iprot.readListBegin();
                    _val6 = new ArrayList<Column>(_list7.size);
                    for (int _i8 = 0; _i8 < _list7.size; ++_i8)
                    {
                      Column _elem9;
                      _elem9 = new Column();
                      _elem9.read(iprot);
                      _val6.add(_elem9);
                    }
                    iprot.readListEnd();
                  }
                  struct.columns.put(_key5, _val6);
                }
                iprot.readMapEnd();
              }
              struct.setColumnsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Metamodel struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.partitionGroup != null) {
        oprot.writeFieldBegin(PARTITION_GROUP_FIELD_DESC);
        oprot.writeString(struct.partitionGroup);
        oprot.writeFieldEnd();
      }
      if (struct.columnFamilies != null) {
        if (struct.isSetColumnFamilies()) {
          oprot.writeFieldBegin(COLUMN_FAMILIES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.columnFamilies.size()));
            for (String _iter10 : struct.columnFamilies)
            {
              oprot.writeString(_iter10);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.rowKey != null) {
        oprot.writeFieldBegin(ROW_KEY_FIELD_DESC);
        oprot.writeString(struct.rowKey);
        oprot.writeFieldEnd();
      }
      if (struct.columns != null) {
        oprot.writeFieldBegin(COLUMNS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.LIST, struct.columns.size()));
          for (Map.Entry<String, List<Column>> _iter11 : struct.columns.entrySet())
          {
            oprot.writeString(_iter11.getKey());
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, _iter11.getValue().size()));
              for (Column _iter12 : _iter11.getValue())
              {
                _iter12.write(oprot);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MetamodelTupleSchemeFactory implements SchemeFactory {
    public MetamodelTupleScheme getScheme() {
      return new MetamodelTupleScheme();
    }
  }

  private static class MetamodelTupleScheme extends TupleScheme<Metamodel> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Metamodel struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPartitionGroup()) {
        optionals.set(0);
      }
      if (struct.isSetColumnFamilies()) {
        optionals.set(1);
      }
      if (struct.isSetRowKey()) {
        optionals.set(2);
      }
      if (struct.isSetColumns()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetPartitionGroup()) {
        oprot.writeString(struct.partitionGroup);
      }
      if (struct.isSetColumnFamilies()) {
        {
          oprot.writeI32(struct.columnFamilies.size());
          for (String _iter13 : struct.columnFamilies)
          {
            oprot.writeString(_iter13);
          }
        }
      }
      if (struct.isSetRowKey()) {
        oprot.writeString(struct.rowKey);
      }
      if (struct.isSetColumns()) {
        {
          oprot.writeI32(struct.columns.size());
          for (Map.Entry<String, List<Column>> _iter14 : struct.columns.entrySet())
          {
            oprot.writeString(_iter14.getKey());
            {
              oprot.writeI32(_iter14.getValue().size());
              for (Column _iter15 : _iter14.getValue())
              {
                _iter15.write(oprot);
              }
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Metamodel struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.partitionGroup = iprot.readString();
        struct.setPartitionGroupIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list16 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.columnFamilies = new ArrayList<String>(_list16.size);
          for (int _i17 = 0; _i17 < _list16.size; ++_i17)
          {
            String _elem18;
            _elem18 = iprot.readString();
            struct.columnFamilies.add(_elem18);
          }
        }
        struct.setColumnFamiliesIsSet(true);
      }
      if (incoming.get(2)) {
        struct.rowKey = iprot.readString();
        struct.setRowKeyIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map19 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.columns = new HashMap<String,List<Column>>(2*_map19.size);
          for (int _i20 = 0; _i20 < _map19.size; ++_i20)
          {
            String _key21;
            List<Column> _val22;
            _key21 = iprot.readString();
            {
              org.apache.thrift.protocol.TList _list23 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
              _val22 = new ArrayList<Column>(_list23.size);
              for (int _i24 = 0; _i24 < _list23.size; ++_i24)
              {
                Column _elem25;
                _elem25 = new Column();
                _elem25.read(iprot);
                _val22.add(_elem25);
              }
            }
            struct.columns.put(_key21, _val22);
          }
        }
        struct.setColumnsIsSet(true);
      }
    }
  }

}
